### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by mpustovoi**
Added missing translations and aligned tabulation

### CODE REVIEW

**Comment by ellie-semele** [comment]
Thanks for this, will review at some point today, just to confirm are you okay with these being licensed `CC BY-SA 4.0.`? basically anyone can use them as long as they credit you and any future contributions are under the same license.

License short explanation (Russian): https://creativecommons.org/licenses/by-sa/4.0/deed.ru
and in English: https://creativecommons.org/licenses/by-sa/4.0/deed

**Comment by mpustovoi** [comment]
Yes, sure

**Comment by ellie-semele** [comment]
Luckily one of my Russian friends decided to help review this, just curious why the Expanded Storage prefixes were translated to `[РШ]` instead of `[РX]`.

**Comment by mpustovoi** [comment]
My bad. It looks so stupid, so I'd fix that right now

**Comment by ellie-semele** [comment]
Looks good to me, thank you very much for the contribution!

**Pull request merged**
